# Generated by Django 2.2.4 on 2019-08-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='use_ssl',
            field=models.BooleanField(default=True),
        ),
    ]
