# Generated by Django 2.2.4 on 2019-08-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0003_auto_20190820_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='reply_to',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
