# Generated by Django 2.2.4 on 2019-08-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmail', '0004_auto_20190815_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='sent_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
